ethersphere/storage-incentives

test/PostageStamp.test.ts, test/PriceOracle.test.ts
tests for postage stamp and price oracle
=> add postage stamp tests

.github/workflows/codegen.yml, codegen/go.sh, hardhat.config.ts
=> add codegen

README.md, package.json
Description: Detailed steps to test and deploy smart contracts and minor additions to package.json
=> refactor: readme file

.env.example, README.md, hardhat.config.ts
Unifies the wallet mnemonic and private key to a single .env variable.
=> feat: unify mnemonic and private key to .env wallet secret

.github/workflows/ci.yml, package.json, test/Stats.test.ts
=> refactor: stats test

README.md, hardhat.config.ts
**Summary:**
Minor additions to read me file.
=> refactor: notes in read me

src/Redistribution.sol, test/Redistribution.test.ts
ESLinting in `Redistribution.test.ts`, tests for pausing contract and **Pausing Functionality** in `Redistribution.sol` contract.
=> refactor: add pauser role for redistribution contract

test/PostageStamp.test.ts, test/util/tools.ts
=> test: re-introduce deleted copyBatch test suite

src/Redistribution.sol
a more forgiving approach, for the time being 👼
=> feat: reduce freezing length

scripts/deploy_redis.ts
Block number is not propagated properly in current code, so this fixes it.
=> fix to get proper block number

mainnet_deployed.json, scripts/deployer.ts
Current network IDs are wrongly set so I changed them
https://chainid.network/chains.json
=> fix: change IDs, current ones are wrong

hardhat.config.ts, package.json, yarn.lock
Add 2 new tools to env. One is for the preprocessing of code before deployment which removes console logs if any have been left by mistake. The other is a contract sizer that shows how big in kb the contracts are, helps with optimization.
=> feat: Extra tooling

hardhat.config.ts, helper-hardhat-config.ts
Just putting proper sepolia params and using it as default testnet network.
=> feat: use sepolia as tesnet

.gitignore, hardhat.config.ts, package.json, yarn.lock
Adding tooling here so we can measure gas used per functions and optimize when needed.
=> feat: add gas reports

src/PriceOracle.sol, test/PriceOracle.test.ts, test/Redistribution.test.ts, test/util/tools.ts
Was done on top of the branch where we have skipped rounds included.
Reworked tests to reflect the changes.
=> fix(oracle): change rate of price modulations 

src/PostageStamp.sol
=> fix: typo-on-natspec

src/PriceOracle.sol
Same pattern and reasoning applied as here
https://github.com/ethersphere/storage-incentives/pull/159
view here
https://github.com/ethersphere/storage-incentives/blob/6c1002e5bca3caf8e40dbb5d9b4a91d9e82e5fe4/src/PriceOracle.sol
=> style: oracle

src/Staking.sol
Same pattern and reasoning applied as here
https://github.com/ethersphere/storage-incentives/pull/159
view here
https://github.com/ethersphere/storage-incentives/blob/61fb465c5bb3a1c6da88f0e4da71748e9c456352/src/Staking.sol
=> style: staking

hardhat.config.ts, tasks/index.ts, tasks/signatures.ts, tsconfig.json
make hardhat task for exporting signatures
=> Feat: hh task sigs

src/PostageStamp.sol
Fixing per issue here
https://github.com/ethersphere/storage-incentives/issues/156
=> fix: remove immutable check on storage increase

deploy/main/011_deploy_state_changes.ts, deploy/test/011_deploy_state_changes.ts, src/Redistribution.sol
in case of Bee reserve size would raise in the future, we may need to adjust the reserve estimation for the new size.
=> feat(redis): set sample max value

deploy/main/011_deploy_multisig.ts
add roles grant and renouncing
=> fix: small addition to infra

hardhat.config.ts, src/Staking.sol, test/Staking.test.ts
Change a structure of Staking and also add gas optimizations, custom errors etc
=> feat: Staking optimization, code and gas golfing

src/PriceOracle.sol
emit event for price update so bee node catches price on new contract deployment
=> task: emit event for price

tasks/signatures.ts
Simple tooling fix for extracting signatures locally
=> fix: add better sig info
